CREATE TYPE "appointment_status" AS ENUM (
  'PROGRAMMED',
  'ATTENDED',
  'NOT_ATTENDED'
);

CREATE TABLE "patient" (
  "patient_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "identification" varchar(20) UNIQUE NOT NULL,
  "first_name" varchar(90) NOT NULL,
  "last_name" varchar(90) NOT NULL,
  "email" varchar(200) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "address" varchar(200) NOT NULL,
  "city" varchar(90) NOT NULL,
  "active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "doctor" (
  "doctor_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "identification" varchar(20) UNIQUE NOT NULL,
  "first_name" varchar(90) NOT NULL,
  "last_name" varchar(90) NOT NULL,
  "email" varchar(200) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "address" varchar(200) NOT NULL,
  "city" varchar(90) NOT NULL,
  "professional_card_number" varchar(20) NOT NULL,
  "admission_date" timestamp NOT NULL,
  "active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "doctor_availability" (
  "availability_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int NOT NULL,
  "date" timestamp NOT NULL,
  "available" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "appointment" (
  "appointment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" timestamp NOT NULL,
  "status" appointment_status NOT NULL,
  "patient_id" int NOT NULL,
  "doctor_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "specialty" (
  "specialty_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "medical_order" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(500) NOT NULL,
  "expiration_date" timestamp NOT NULL,
  "specialty_id" int NOT NULL,
  "appointment_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "medicine" (
  "medicine_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" varchar(500) NOT NULL
);

CREATE TABLE "medical_order_medicine" (
  "order_id" int NOT NULL,
  "medicine_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

COMMENT ON TABLE "patient" IS 'Tabla de pacientes';

COMMENT ON COLUMN "patient"."patient_id" IS 'Identificador único. Este campo se genera automáticamente cuando se crea un nuevo paciente';

COMMENT ON COLUMN "patient"."identification" IS 'Identificación del paciente';

COMMENT ON COLUMN "patient"."first_name" IS 'Nombre del paciente';

COMMENT ON COLUMN "patient"."last_name" IS 'Apellido del paciente';

COMMENT ON COLUMN "patient"."email" IS 'Correo electrónico de contacto';

COMMENT ON COLUMN "patient"."phone" IS 'Teléfono de contacto';

COMMENT ON COLUMN "patient"."address" IS 'Dirección del paciente';

COMMENT ON COLUMN "patient"."city" IS 'Ciudad de residencia';

COMMENT ON COLUMN "patient"."active" IS 'Paciente activo o inactivo';

COMMENT ON COLUMN "patient"."created_at" IS 'Fecha de creación del paciente';

COMMENT ON COLUMN "patient"."updated_at" IS 'Fecha de modificación del paciente';

COMMENT ON TABLE "doctor" IS 'Tabla de médicos';

COMMENT ON COLUMN "doctor"."doctor_id" IS 'Identificador único. Este campo se genera automáticamente cuando se crea un nuevo médico';

COMMENT ON COLUMN "doctor"."identification" IS 'Identificación del médico';

COMMENT ON COLUMN "doctor"."first_name" IS 'Nombre del médico';

COMMENT ON COLUMN "doctor"."last_name" IS 'Apellido del médico';

COMMENT ON COLUMN "doctor"."email" IS 'Correo electrónico de contacto';

COMMENT ON COLUMN "doctor"."phone" IS 'Teléfono de contacto';

COMMENT ON COLUMN "doctor"."address" IS 'Dirección del médico';

COMMENT ON COLUMN "doctor"."city" IS 'Ciudad de residencia';

COMMENT ON COLUMN "doctor"."professional_card_number" IS 'Número de la tarjeta profesional';

COMMENT ON COLUMN "doctor"."admission_date" IS 'Fecha de ingreso';

COMMENT ON COLUMN "doctor"."active" IS 'Médico activo o inactivo';

COMMENT ON COLUMN "doctor"."created_at" IS 'Fecha de creación del médico';

COMMENT ON COLUMN "doctor"."updated_at" IS 'Fecha de modificación del médico';

COMMENT ON TABLE "doctor_availability" IS 'tabla de horarios disponibles del doctor para citas médicas.';

COMMENT ON COLUMN "doctor_availability"."availability_id" IS 'Identificador único. Este campo se genera automáticamente cuando se agrega un nuevo horario';

COMMENT ON COLUMN "doctor_availability"."doctor_id" IS 'Id del médico';

COMMENT ON COLUMN "doctor_availability"."date" IS 'Fecha del horario';

COMMENT ON COLUMN "doctor_availability"."available" IS 'Campo que notifica si un médico esta disponible o no';

COMMENT ON COLUMN "doctor_availability"."created_at" IS 'Fecha de creación de la disponibilidad del médico';

COMMENT ON COLUMN "doctor_availability"."updated_at" IS 'Fecha de modificación de la disponibilidad del médico';

COMMENT ON TABLE "appointment" IS 'Tabla de citas médicas';

COMMENT ON COLUMN "appointment"."appointment_id" IS 'Identificador único. Este campo se genera automáticamente cuando se crea una cita médica';

COMMENT ON COLUMN "appointment"."date" IS 'Fecha de la cita médica';

COMMENT ON COLUMN "appointment"."status" IS 'Estado de la cita médica';

COMMENT ON COLUMN "appointment"."patient_id" IS 'Id del paciente';

COMMENT ON COLUMN "appointment"."doctor_id" IS 'Id del médico';

COMMENT ON COLUMN "appointment"."created_at" IS 'Fecha de creación de la cita médica';

COMMENT ON COLUMN "appointment"."updated_at" IS 'Fecha de modificación de la cita médica';

COMMENT ON TABLE "specialty" IS 'Tabla de especialidades médicas';

COMMENT ON COLUMN "specialty"."specialty_id" IS 'Identificador único. Este campo se genera automáticamente cuando se crea una especialidad médica';

COMMENT ON COLUMN "specialty"."name" IS 'Nombre d ela especialidad';

COMMENT ON COLUMN "specialty"."created_at" IS 'Fecha de creación de la especialidad médica';

COMMENT ON COLUMN "specialty"."updated_at" IS 'Fecha de modificación de la especialidad médica';

COMMENT ON TABLE "medical_order" IS 'Tabla de ordenes médicas';

COMMENT ON COLUMN "medical_order"."order_id" IS 'Identificador único. Este campo se genera automáticamente cuando se crea una orden médica';

COMMENT ON COLUMN "medical_order"."description" IS 'Descripción de la orden médica';

COMMENT ON COLUMN "medical_order"."expiration_date" IS 'Fecha de vencimiento de la orden médica';

COMMENT ON COLUMN "medical_order"."specialty_id" IS 'Id de la especialidad médica';

COMMENT ON COLUMN "medical_order"."appointment_id" IS 'Id de la cita médica';

COMMENT ON COLUMN "medical_order"."created_at" IS 'Fecha de creación de la orden médica';

COMMENT ON COLUMN "medical_order"."updated_at" IS 'Fecha de modificación de la orden médica';

COMMENT ON TABLE "medicine" IS 'Tabla de oproductos de medicina';

COMMENT ON COLUMN "medicine"."medicine_id" IS 'Identificador único. Este campo se genera automáticamente cuando se agrega un producto de medicina';

COMMENT ON COLUMN "medicine"."name" IS 'Nombre del producto de medicina';

COMMENT ON COLUMN "medicine"."description" IS 'Descripción del producto de medicina';

COMMENT ON TABLE "medical_order_medicine" IS 'Tabla de relación entre ordenes médicas y la medicina';

COMMENT ON COLUMN "medical_order_medicine"."order_id" IS 'Id de la orden médica';

COMMENT ON COLUMN "medical_order_medicine"."medicine_id" IS 'Id de la medicina';

COMMENT ON COLUMN "medical_order_medicine"."created_at" IS 'Fecha de creación';

COMMENT ON COLUMN "medical_order_medicine"."updated_at" IS 'Fecha de modificación';

ALTER TABLE "doctor_availability" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctor" ("doctor_id");

ALTER TABLE "appointment" ADD FOREIGN KEY ("patient_id") REFERENCES "patient" ("patient_id");

ALTER TABLE "appointment" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctor" ("doctor_id");

ALTER TABLE "medical_order" ADD FOREIGN KEY ("specialty_id") REFERENCES "specialty" ("specialty_id");

ALTER TABLE "medical_order" ADD FOREIGN KEY ("appointment_id") REFERENCES "appointment" ("appointment_id");

ALTER TABLE "medical_order_medicine" ADD FOREIGN KEY ("order_id") REFERENCES "medical_order" ("order_id");

ALTER TABLE "medical_order_medicine" ADD FOREIGN KEY ("medicine_id") REFERENCES "medicine" ("medicine_id");